# Replace the text below to customize your site
site_name: Isabel Allaert
site_description: Isabel Allaert's Fabricademy site
site_author: Isabel Allaert
copyright: Copyright 2022 Isabel Allaert - Creactive Commons Attribution Non-commercial

site_url: https://class.textile-academy.org/2022/isabel-allaert/
repo_url: https://gitlab.fabcloud.org/academany/fabricademy/2022/students/isabel-allaert
repo_name: fabricademy/2022/isabel-allaert

extra:
  social:
    # Change to your own social media or remove some. For more social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabricademy
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabricademy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabricademy

theme:
  # The name of the theme, check your requirements.txt file
  name: material
  palette:
    # try other colors from https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: cyan
    accent: pink
  font:
    # See available fonts from https://fonts.google.com/
    text: Overpass
    code: Ubuntu Mono
  icon:
    # Read about icons at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
    logo: material/library
    repo: material/gitlab
    favicon: images/favicon.svg
  features:
    # See more about the navigation at https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI

# See more extensions at https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
